### ISSUE TITLE
Code review before publishing

### ISSUE THREAD

**Issue by Planeshifter** [compute-io/to-array#1]

**Comment by kgryte** [comment]
Made some updates. Most notably, now checks for an empty `matrix`. Before if `mat.shape[ 0 ] !== 0` but `mat.shape[ 1 ] === 0`, then would return an array of empty arrays. If the opposite was true, would return an empty array. Here, a decision is proposed to return an empty array in _both_ cases.

**Comment by kgryte** [comment]
If, after your review, all looks good, feel free to publish.
