### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [compute-io/to-array#3]
Changed module name to `dstructs-to-array`. Module should be reviewed to ensure everything has been appropriately cutover.

Question: in its original development, the idea was for `to-array` to convert different data structures into an `array` of `arrays`. Currently, only `matrix` data structures are supported. Should the module name be `dstructs-matrix-to-array`, similar to `dstructs-typed-array-to-json`?

If so, suppose we create a `dstructs-dframe-to-array`, the modules for `matrix` and `dframe` conversion could be combined into a separate `dstructs-to-array`.

Currently, the module name mirrors [`to-matrix`](https://github.com/compute-io/to-matrix).

**Comment by Planeshifter** [comment]
Looks good to me. Re: other input data structures, why not simply adding the functionality to this module? The sole advantage of having a smaller browserified file does not outweigh the costs of having to require different modules, I think.

**Comment by kgryte** [comment]
Sure. Neither option atm precludes us from changing course later.

**Comment by Planeshifter** [comment]
Fair point. Publish to npm?

**Comment by kgryte** [comment]
Done.
